version: "3.5"

services:
  akhq:
    image: tchiotludo/akhq:latest
    hostname: akhq
    networks:
      - workshop
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka-1:9092, kafka-2:9092, kafka-3:9092"
                
    ports:
      - 8080:8080

networks:
  workshop: