version: "3.5"
services:
  jconsole:
    build: ./jconsole/.
    hostname: jconsole
    networks:
      - workshop
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
    command: "bash -c 'jconsole kafka-1:1098'"

networks:
  workshop: