global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    scrape_interval: 10s
    static_configs:
      - targets: ['']
  - job_name: 'zookeeper'
    scrape_interval: 10s
    static_configs:
      - targets: ['']