{
 "title": "Kafka Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Aggregate incoming byte rate.",
   "type": "graph",
   "description": "Aggregate incoming byte rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Data rate" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesin_total[1m]) and {topic = \"my-topic\" }",
     "legendFormat": "{{ instance }} - {{ topic }}"
    }
   ]
  },
  {
   "title": "Aggregate outgoing byte rate.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Data rate" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_bytesout_total[5m]) and {topic = \"my-topic\" }",
     "legendFormat": "{{ instance }} - {{ topic }}"
    }
   ]
  },
  {
   "title": "Aggregate incoming message rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{ topic = \"my-topic\" }",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Lag in number of messages per follower replica.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_fetcherlagmetrics_consumerlag and {topic = \"my-topic\" }",
     "legendFormat": "{{ instance }} {{ topic }}"
    }
   ]
  },
  {
   "title": "ISR Shrinks. If a broker goes down, ISR for some of the partitions will shrink. ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_replicamanager_isrshrinks_total[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "ISR Expands. When a broker is brought up after a failure, it starts catching up by reading from the leader.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_replicamanager_isrexpands_total[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Unclean Leader Elections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_controller_controllerstats_uncleanleaderelections_total[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Zookeeper Total Session Expires",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_sessionexpirelistener_zookeeperexpires_total[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Request Handler Avg IdlePercent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Partition Under Replicated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_cluster_partition_underreplicated and {topic = \"my-topic\" }",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Partition offline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}